import streamlit as st
from data_mcp.tools import get_stock_fundamentals
from analysis.fundamentals import generate_investment_memo

def render_fundamentals_tab(ticker):
    st.header(f"📊 Fundamental Analysis: {ticker}")
    st.caption("Generated by Senior Equity Research Analyst Module")
    
    if st.button("Generate Investment Memo"):
        with st.spinner("Analyzing Financial Statements..."):
            info, financials = get_stock_fundamentals(ticker)
            report = generate_investment_memo(ticker, info, financials)
            st.markdown(report)
            
            with st.expander("View Raw Financial Data"):
                st.write("Income Statement", financials.get('income_statement'))
                st.write("Balance Sheet", financials.get('balance_sheet'))
                st.write("Cash Flow", financials.get('cash_flow'))
